### ISSUE TITLE
[Enhancement] Add the possibility to change the bar code color

### ISSUE THREAD

**Issue by Leo-Peyronnet** [Leo-Corporation/Gerayis#10]
**Enhancement:**
Add the possibility to change the bar code color.

**Describe the solution:**
Add a section in the "Settings" page with:

- [x] The possibility to set the foreground color
- [x] The possibility to set background color
- [x] The possibility to reset to the default values
